# name: Build and Test Java Spring Boot Application 
 
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
 
# # jobs:
# #         build:
      
# #           runs-on: ubuntu-latest
      
# #           steps:
# #           - uses: actions/checkout@v2
# #           - name: Set up JDK 1.8
# #             uses: actions/setup-java@v1
# #             with:
# #               java-version: '1.8'
# #               distribution: 'adopt'
# #               cache: maven
# #           - name: Build with Maven
# #             run: mvn clean --file *.pom

# # jobs:
# #     build:
  
# #       runs-on: ubuntu-latest
  
# #       steps:
# #       - uses: actions/checkout@v3
      
# #       - name: Set up JDK 11
# #         uses: actions/setup-java@v3
# #         with:
# #           java-version: '11'
# #           distribution: 'zulu'
# #           cache: maven
      
# #       - name: Build with Maven
# #         run: mvn -B package jacoco:report --file pom.xml -Daem.analyser.strict=true
# jobs:
#     build:
  
#       runs-on: ubuntu-latest
  
#       steps:
#         - name: Check out the repository
#           uses: actions/checkout@v4
#         - name: Set up JDK 17
#           uses: actions/setup-java@v3
#           with:
#             java-version: '17'
#             distribution: 'temurin'
#             cache: maven
#         - name: Build and test with Maven
#           run: mvn --batch-mode -X package


# name: Java Maven Build & Publish Artifact

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build_test:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         cache: maven
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml

   
#   publish-job:
#     runs-on: ubuntu-latest
#     needs: build_test
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#     - run: mvn --batch-mode --update-snapshots verify
#     - run: mkdir staging && cp target/*.jar staging
#     - uses: actions/upload-artifact@v3
#       with:
#         name: Package
#         path: staging
name: Build and Test Java Spring Boot Application 
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean verify
 
    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: SpringBoot Report               # Name of the folder
          path: target/site/serenity/           # Path to test results